language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-source
  - composer require satooshi/php-coveralls '~1.0'

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_success: php vendor/bin/coveralls
