language: php

php:
  - 8.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --no-interaction --prefer-source
  - composer require satooshi/php-coveralls

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_success: php vendor/bin/coveralls
